package grammar

const (
	LogicalAnd                 = "&&"
	LogicalOr                  = "||"
	RangeCommentOpen           = "#>"
	RangeCommentClose          = "<#"
	IntegerDivision            = "//"
	IntegerDivideWithBigger    = "\\\\"
	Exponentiation             = "**"
	Equals                     = "=="
	NotEquals                  = "<>"
	GreaterEquals              = ">="
	LessEquals                 = "<="
	Params                     = "..."
	LeftBinaryShift            = "<<"
	RightBinaryShift           = ">>"
	AdditionAssignment         = "+="
	SubtractionAssignment      = "-="
	MultiplicationAssignment   = "*="
	ExponentiationAssignment   = "**="
	DivisionAssignment         = "/="
	ModulusAssignment          = "%="
	LeftBinaryShiftAssignment  = "<<="
	RightBinaryShiftAssignment = ">>="
	InclusiveOrAssignment      = "|="
	XOrAssignment              = "^="
	AndAssignment              = "&="
)
