package grammar

const (
	TokenSharp       = "#"
	TokenPlus        = "+"
	TokenMinus       = "-"
	TokenStar        = "*"
	TokenPercent     = "%"
	TokenSlash       = "/"
	TokenBackslash   = "\\"
	TokenEquals      = "="
	TokenVerticalBar = "|"
	TokenGreat       = ">"
	TokenLess        = "<"
	TokenSemicolon   = ";"
	TokenColon       = ":"
	TokenComma       = ","
	TokenExclamation = "!"
	TokenAmper       = "&"
	TokenDot         = "."
	TokenLParenthes  = "("
	TokenRParenthes  = ")"
	TokenLBrace      = "{"
	TokenRBrace      = "}"
	TokenLBracket    = "["
	TokenRBracket    = "]"
	TokenDoubleQuote = "\""
	TokenQuote       = "'"
	TokenCaret       = "^"
	TokenUnderscore  = "_"
)
